/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BenchCheckpointSnapshotTier {
  static create(backend: BenchMemoryBackend, name?: string | undefined | null, compactEvery?: number | undefined | null): BenchCheckpointSnapshotTier
  /** Save a checkpoint record (JSON). */
  save(recordJson: string): void
  /** Load the latest checkpoint record (JSON or null). */
  load(): string | null
  flush(): void
  rollback(): void
  get name(): string
}

export declare class BenchCore {
  /**
   * Construct a fresh `BenchCore` wired to a Rust-side value registry.
   *
   * **S6/D255:** the actor's worker thread spawns inside
   * `CoreActor::spawn(binding)` and constructs the `Core` on the
   * worker (Core is `!Send`, so it must be born on the thread that
   * owns it). This constructor returns immediately; the worker is
   * ready to receive closures by the time any subsequent napi
   * method's first `actor.run(...)` resolves.
   */
  constructor()
  /**
   * Intern an i32 value; returns its HandleId. Used by JS-side
   * adapters to construct fresh handles for operator callback returns
   * (e.g., `register_map(src, x => intern_int(deref_int(x) + 1))`).
   */
  internInt(value: number): number
  /**
   * Dereference a HandleId to its i32 payload. Returns -1 for
   * unknown handles or non-Int values (matches `cache_int`'s
   * sentinel convention for the bench surface).
   */
  derefInt(handle: number): number
  /**
   * Allocate a fresh handle for the JS adapter to associate with a
   * JS-side value (D073). Returns the handle ID; refcount=1.
   * **Caller responsibility:** the JS adapter MUST register the
   * value in its mirror map BEFORE handing the handle to anything
   * that may dereference it (operator callbacks, sinks).
   * Sync — pure Registry op, no Core wave.
   */
  allocExternalHandle(): number
  /**
   * Register a state node initialized with a JS-allocated handle.
   * JS adapter must have called `alloc_external_handle` and stored
   * the value in its mirror first. The handle's refcount=1 share is
   * consumed by the state node's initial cache slot.
   */
  registerStateWithHandle(initialHandle: number): Promise<number>
  /**
   * Emit a JS-allocated handle on a node. JS adapter must have
   * stored the value in its mirror first. The handle's refcount
   * share is consumed by Core's emission path (Core retains the
   * handle into the cache slot).
   */
  emitHandle(nodeId: number, handle: number): Promise<void>
  /**
   * Read a node's current cache as a HandleId. Returns 0
   * (NO_HANDLE) for sentinel cache. JS adapter looks up the handle
   * in its mirror map.
   */
  cacheHandle(nodeId: number): Promise<number>
  /** Register a state node with an i32 initial value. */
  registerStateInt(initial: number): Promise<number>
  /** Register a state node with sentinel cache (no initial value). */
  registerStateSentinel(): Promise<number>
  /** Register a derived node with a built-in fn shape. */
  registerDerived(depIds: Array<number>, builtin: BuiltinFn): Promise<number>
  /**
   * Subscribe a noop sink. Activation may fire fns (including
   * JS-callback operators), so this MUST be async.
   *
   * **S6 / D241+D255 reconciled:** Core::subscribe now returns a
   * `SubscriptionId` (D241) — the substrate-level RAII `Subscription`
   * type was deleted in D225. We post the subscribe through the
   * actor and record the `(NodeId, SubscriptionId)` pair so the
   * matching unsubscribe in `BenchCore::unsubscribe` / `dispose` /
   * `Drop` can call `Core::unsubscribe(node_id, sub_id)` explicitly.
   *
   * **D248 sink-shape note:** `graphrefly_core::Sink =
   * Arc<dyn Fn(&[Message])>` (without `Send + Sync`) — owner-thread-
   * only. We build the sink *inside* the actor closure, on the
   * worker thread, so the `!Send` Sink never has to cross the
   * actor channel.
   */
  subscribeNoop(nodeId: number): Promise<number>
  /**
   * Subscribe with a JS callback sink (D077). The callback receives
   * a flat-encoded `Vec<u32>` per message batch — alternating
   * `(variantCode, payload)` pairs. JS adapter decodes via the
   * `MSG_CODE_*` table (mirrored in `rust.ts`) and dereferences
   * payload handles via the JS-side mirror map.
   *
   * **Sync-bridge semantics:** the returned Promise resolves AFTER
   * the subscribe-time handshake fires AND the JS sink callback
   * completes (per `bridge_sync_unit` blocking the actor worker on
   * a sync_channel until JS responds via libuv pump). JS code
   * MUST `await` this method — synchronous calling deadlocks.
   *
   * `pub fn` (not `async fn`) because `Function<'_, >` is `!Send`; the
   * async work runs inside `env.spawn_future(async move { ... })`.
   *
   * **D248 sink-shape:** the `tsfn: Arc<SinkTsfn>` we move into the
   * actor closure IS `Send + Sync` (`ThreadsafeFunction` is
   * Send+Sync by napi-rs design); the `Sink = Arc<dyn Fn(&[Message])>`
   * that wraps it is `!Send`, so we build it on the worker thread
   * inside the actor closure.
   */
  subscribeWithTsfn(nodeId: number, sinkCallback: (arg: Array<number>) => void): Promise<number>
  /**
   * Install the JS-side prune callback (D076). Called once at JS
   * adapter construction. Subsequent calls overwrite. The callback
   * receives a single `(handle: u32)` and should `Map.delete(handle)`
   * in the JS-side mirror. Fired NON-BLOCKING from
   * `BindingBoundary::release_handle`.
   */
  setReleaseCallback(callback: (arg: number) => void): void
  /**
   * Drop the subscription at `idx` (releases activation refcount).
   * Posts the unsubscribe through the actor so the JS thread stays
   * free to pump libuv if the unsubscribe triggers terminal-cascade
   * work that fires TSFN-backed sinks.
   *
   * **S6 / D241+D255 reconciled:** explicit `Core::unsubscribe(node,
   * sub_id)` replaces the deleted `impl Drop for Subscription`
   * (D225).
   */
  unsubscribe(idx: number): Promise<void>
  /**
   * Drain all retained subscriptions through the actor — JS code
   * MUST `await core.dispose()` before letting `BenchCore` drop.
   * Closes the BenchCore::Drop deadlock vector (Slice Y): without
   * `dispose`, GC of the napi instance runs `Drop` on the JS thread;
   * each unsubscribe would post to the actor and *not* be able to
   * `.await` (Drop is sync). The actor's worker thread would still
   * run the work fire-and-forget, but the JS thread would have
   * already moved on without ensuring terminal-cascade TSFNs
   * flushed. Calling `dispose` first guarantees the JS thread waits
   * for the cascade to settle.
   *
   * Idempotent: subsequent calls are no-ops once the vec is drained.
   */
  dispose(): Promise<void>
  /** Emit an i32 value on a state node. */
  emitInt(nodeId: number, value: number): Promise<void>
  /** Read a state node's current cache as i32. */
  cacheInt(nodeId: number): Promise<number>
  /** Tight loop: emit `n` times on a state node, no JS call between. */
  rustEmitLoop(nodeId: number, n: number): Promise<void>
  allocLockId(): Promise<number>
  setPauseBufferCap(cap?: number | undefined | null): Promise<void>
  pause(nodeId: number, lockId: number): Promise<void>
  resume(nodeId: number, lockId: number): Promise<ResumeReportJs | null>
  isPaused(nodeId: number): Promise<boolean>
  /**
   * Number of pause locks currently held. Returns Err on overflow
   * instead of saturating silently (M8 fix — matches `alloc_lock_id`).
   */
  pauseLockCount(nodeId: number): Promise<number>
  holdsPauseLock(nodeId: number, lockId: number): Promise<boolean>
  invalidate(nodeId: number): Promise<void>
  complete(nodeId: number): Promise<void>
  /**
   * Emit ERROR with a JS-allocated handle (D076 parity — non-i32 error
   * payloads). JS adapter must have called `alloc_external_handle` and
   * stored the value first. The handle's refcount share is consumed by
   * Core's error path.
   */
  errorHandle(nodeId: number, handle: number): Promise<void>
  errorInt(nodeId: number, errCode: number): Promise<void>
  teardown(nodeId: number): Promise<void>
  addMetaCompanion(parent: number, companion: number): Promise<void>
  setResubscribable(nodeId: number, resubscribable: boolean): Promise<void>
  batchEmitInts(nodeId: number, values: Array<number>): Promise<void>
  setDeps(nodeId: number, newDepIds: Array<number>): Promise<void>
  hasFiredOnce(nodeId: number): Promise<boolean>
  /**
   * Register a derived node whose fn returns `FnResult::Batch`.
   * R1.3.6.b — multi-emit per fire flows in same wave.
   */
  registerBatchDerived(depIds: Array<number>, builtin: BuiltinBatchFn): Promise<number>
  /**
   * Batch-dispatch a handle-encoded message sequence atomically (Phase E
   * /qa F2 — D077 "one call = one wave"). The `encoded` argument is a
   * flat `[code_0, payload_0, code_1, payload_1, ...]` array using the
   * same `MSG_CODE_*` table that `subscribe_with_tsfn` decodes — so
   * `RustNode.down(msgs)` can encode once on the JS side and replay
   * the whole batch through one Core wave.
   *
   * Codes accepted:
   * - 1 (DIRTY) — Core auto-emits DIRTY before tier-3 emissions; an
   *   explicit DIRTY in `encoded` is a no-op (matches legacy semantics).
   * - 3 (DATA) — payload is a JS-allocated handle (D073).
   * - 4 (INVALIDATE) — no payload.
   * - 5 (PAUSE) — payload is a lock id.
   * - 6 (RESUME) — payload is a lock id.
   * - 7 (COMPLETE) — no payload.
   * - 8 (ERROR) — payload is a JS-allocated handle.
   * - 9 (TEARDOWN) — no payload.
   *
   * Codes 0 (Start), 2 (Resolved) are not accepted on the down-path
   * (legacy parity — Start is per-subscription, Resolved is generated
   * by Core's equals path).
   */
  batchEmitHandleMessages(nodeId: number, encoded: Array<number>): Promise<void>
  batchEmitMessages(nodeId: number, msgs: Array<BatchEmissionJs>): Promise<void>
  /**
   * Single-node describe projection (N1 `describeNode`).
   *
   * **D207 (locked 2026-05-15): REUSE the existing snapshot /
   * describe-projection path — no new `graphrefly-core` public
   * method.** This composes Core's existing *read-side inspection
   * helpers* (`kind_of` / `deps_of` / `cache_of` / `has_fired_once`
   * / `is_terminal`) — the very accessors that back
   * `Graph::describe` (`graphrefly-graph::describe::describe_inner`)
   * — into the per-node JSON slice the `Impl.describeNode(node)`
   * contract expects. Mirrors the pure-ts reference arm
   * (`pure-ts.ts` `describeNode → legacy.describeNode(node.inner)`),
   * which returns the same `{ type, status, deps, value? }` shape.
   *
   * Sync — pure read accessors, single state-lock acquire each, no
   * wave entry, no binding callbacks. Returns a JSON string the
   * JS wrapper parses (same marshaling convention as
   * `BenchGraph::describe_json`). Dep ids surface as raw `NodeId`
   * u64s (the namespace lives at the Graph layer; an unattached
   * node has no names — the JS wrapper renders them as
   * `_anon_<id>`, matching `describe_inner`'s unnamed-dep rule).
   *
   * **S6/D255 — actor-routed sync:** under the actor model `&Core`
   * is owner-thread-only, so the read accessors execute on the
   * actor worker thread via [`CoreActor::run_sync`]. The libuv
   * thread blocks briefly on the reply (microseconds for the 5
   * read accessors). The safe-use contract (read-only, no
   * TSFN-active wave interleave) is met by `describe_node`'s
   * inspection-only usage — see `CoreActor::run_sync` docs.
   */
  describeNode(nodeId: number): string
  /**
   * Hex SHA-256 (N1 `sha256Hex`).
   *
   * Hashing is **synchronous in `graphrefly-core`**
   * ([`graphrefly_core::sha256_hex`]) — there is nothing async about
   * SHA-256, and Core forbids a tokio runtime (CLAUDE.md invariant 4
   * / D070 / D077). Async-everywhere is a *binding-contract* shape
   * (`Impl.sha256Hex` is `Promise<string>`), so the async wrapping
   * lives only here at the napi boundary. **Hashing is Core-free**
   * — it does NOT touch the actor / `Core` / WORKER_EXTRAS. We
   * route through `napi::bindgen_prelude::spawn_blocking` (the
   * generic tokio blocking pool, NOT the actor's pinned worker)
   * just to keep the (potentially large) input hashing off the
   * libuv thread. (QA fix 2026-05-20 m4: doc previously claimed
   * "we route through the actor" — false; corrected to match the
   * actual `spawn_blocking` body.)
   */
  sha256Hex(input: Uint8Array): Promise<string>
}

/**
 * Handle for a reactive describe subscription. JS code MUST `await
 * dispose()` before letting it drop — D246 r3 owner-invoked detach
 * (no RAII below the binding). `Drop` is a defense-in-depth
 * fire-and-forget detach via `dispatch_detached`.
 */
export declare class BenchDescribeReactiveHandle {
  /**
   * Owner-invoked synchronous detach (D246 r3). Idempotent —
   * subsequent calls find no entry in `WORKER_EXTRAS` and no-op.
   */
  dispose(): Promise<void>
}

/**
 * JS-facing wrapper around a `graphrefly_graph::Graph` (S6/D255).
 *
 * Each `BenchGraph` shares its `BenchCore`'s `Arc<CoreActor>` + value
 * registry + binding so nodes registered through `BenchGraph::state(...)`
 * are visible to `BenchOperators::register_*(...)` and vice-versa.
 * The actual `Graph` instance (which is `!Send + !Sync`) lives in
 * the actor's `WORKER_EXTRAS` thread-local on the worker thread,
 * keyed by [`Self::graph_key`].
 */
export declare class BenchGraph {
  /**
   * Construct a fresh root graph wired to a `BenchCore`'s binding +
   * actor (D074 + D255). The BenchGraph SHARES the BenchCore's
   * actor — nodes registered through `BenchGraph::state(...)` are
   * visible to operator factories on the same `BenchCore`.
   *
   * **Note:** this constructor blocks the JS thread briefly (one
   * sync_channel round-trip with the actor) to install the Graph
   * in `WORKER_EXTRAS`. The work is trivial (one `Graph::new` +
   * HashMap insert); blocking is acceptable for a one-shot factory
   * call.
   *
   * **F14 invariant (restored 2026-05-20 QA F9/m12, preserved by
   * construction):** the `binding: Arc<BenchBinding>` field and
   * the actor's Core's `BindingBoundary` upcast come from the
   * SAME `Arc<BenchBinding>` — both `core.actor_arc()` and
   * `core.binding_arc()` clone fields owned by the supplied
   * `BenchCore`. `BenchCore::new` is the single construction path
   * for that Arc; no public API mints a divergent binding.
   */
  static fromCore(core: BenchCore, name: string): BenchGraph
  name(): string
  nodeCount(): number
  nodeNames(): Array<string>
  childNames(): Array<string>
  isDestroyed(): boolean
  /** Resolve a path to a NodeId; returns 0 (NO_NODE) if missing. */
  tryResolve(path: string): number
  /**
   * Reverse lookup: returns the local name for a NodeId, or None
   * if unnamed in this graph.
   */
  nameOf(nodeId: number): string | null
  /**
   * `state(name, initial_handle?)`. `None` → sentinel cache.
   * Caller (JS adapter) holds the handle's refcount via
   * `BenchCore::alloc_external_handle`; ownership transfers here.
   */
  state(name: string, initialHandle?: number | undefined | null): Promise<number>
  /**
   * `derived(name, deps, builtin)` — uses a built-in fn from
   * `BuiltinFn` (Identity / AddOne) since we don't take JS callbacks
   * here. For real JS-callback derived nodes, callers go through
   * `BenchOperators` operators (map/filter/etc.) and `add(name, id)`
   * the resulting NodeId.
   */
  derived(name: string, depIds: Array<number>, builtin: BuiltinFn): Promise<number>
  /**
   * Register an existing node (e.g., from `BenchOperators::register_map`)
   * under `name` in this graph's namespace.
   *
   * **Async** at the napi boundary (QA fix 2026-05-20, Edge Case
   * Hunter F4 / Blind Hunter M7): `Graph::add` fires
   * `NamespaceChangeSink`s synchronously, and an active
   * `observe_all_reactive` / `attach_snapshot_storage` handle's
   * sink calls `core.subscribe(new_node, sink)`. Under the prior
   * sync `run_sync` shape that subscribe would push the
   * handshake's START to a TSFN-backed sink while libuv is blocked
   * on the actor reply — at best a queue-full silent drop
   * (`NonBlocking max_queue_size=8`), at worst a 3-way deadlock
   * if any sink uses `bridge_sync`. `actor.run` keeps libuv free
   * to pump TSFN microtasks during the await.
   */
  add(name: string, nodeId: number): Promise<number>
  setByName(name: string, handle: number): Promise<void>
  getByName(name: string): Promise<number>
  invalidateByName(name: string): Promise<void>
  completeByName(name: string): Promise<void>
  errorByName(name: string, errorHandle: number): Promise<void>
  remove(name: string): Promise<RemoveAuditJs>
  signalInvalidate(): Promise<void>
  signalPause(lockId: number): Promise<void>
  signalResume(lockId: number): Promise<void>
  /**
   * Atomic-ish signal broadcast over a flat (code, payload) batch
   * (Phase E /qa F3 — D077 server-side input validation). Accepts
   * the same `MSG_CODE_*` table as `batch_emit_handle_messages`,
   * but rejects everything except INVALIDATE / PAUSE / RESUME — the
   * only kinds canonical §3.7.1 supports for graph-wide broadcast.
   */
  signalBatch(encoded: Array<number>): Promise<void>
  /**
   * Mount a fresh empty subgraph under `name`; returns a new
   * `BenchGraph` sharing this graph's actor + binding.
   *
   * Uses [`crate::core_actor::with_extra_try_install_child`] to
   * read the parent + install the child Graph in a SINGLE
   * `WORKER_EXTRAS` `borrow_mut` — avoids the F2-style nested-
   * borrow panic the prior `with_extra` + `install_extra` shape
   * triggered (Edge Case Hunter F2 / Blind Hunter M5, 2026-05-20).
   */
  mountNew(name: string): Promise<BenchGraph>
  /** Detach a previously-mounted subgraph by name. */
  unmount(name: string): Promise<RemoveAuditJs>
  destroy(): Promise<void>
  /**
   * Static edges snapshot — `Vec<(from_name, to_name)>` flattened to
   * alternating `Vec<String>` for napi marshaling.
   *
   * Sync at the napi boundary (preserves `Impl.edges(opts) ->
   * Array<[string, string]>` contract); blocks libuv briefly on the
   * actor reply. Pure read accessor — see [`CoreActor::run_sync`]
   * safe-use contract; the wrapper.js parity-tests usage doesn't
   * interleave with TSFN-active waves.
   */
  edges(recursive: boolean): Array<string>
  /**
   * JSON-serialized describe snapshot. JS adapter parses with
   * `JSON.parse`. Static — for reactive describe, see
   * `describe_reactive`.
   *
   * Sync at the napi boundary (preserves `Impl.describe() ->
   * unknown` contract); same `run_sync` safe-use as `edges`.
   */
  describeJson(): string
  /**
   * Subscribe to live topology snapshots (canonical R3.6.1
   * `describe({ reactive: true })`). Returns a
   * [`BenchDescribeReactiveHandle`]; JS code MUST `await
   * handle.dispose()` (D246 r3 — owner-invoked detach).
   */
  describeReactive(sink: (arg: string) => void): Promise<BenchDescribeReactiveHandle>
  /**
   * Subscribe to all-named-nodes message stream with auto-subscribe
   * on late-added nodes (canonical R3.6.2 `observe(undefined, {
   * reactive: true })`).
   */
  observeAllReactive(sink: (arg0: string, arg1: Array<number>) => void): Promise<BenchObserveReactiveHandle>
  /**
   * Sink-style observe of a single node (canonical R3.6.2 default
   * mode `observe(path)`). When `path` is `None`, fan-out snapshot
   * across all named nodes (no auto-subscribe).
   */
  observeSubscribe(path: string | undefined | null, sink: (arg0: string, arg1: Array<number>) => void): Promise<BenchObserveReactiveHandle>
}

export declare class BenchLogSubscription {
  /**
   * Owner-invoked detach (D246 r3). Idempotent — second call finds
   * no inner ReactiveSub and no-ops. Async to keep the JS thread
   * free during the actor round-trip; `&self` (not `&mut self`)
   * because napi-rs 3 rejects `async fn(&mut self)` without
   * explicit `unsafe`. Interior mutability via `Mutex<Option<…>>`.
   */
  dispose(): Promise<void>
}

export declare class BenchLogView {
  get nodeId(): number
}

/** In-memory storage backend shared across tiers. */
export declare class BenchMemoryBackend {
  constructor()
  /** Read raw bytes for a key (JSON string or null). */
  readRaw(key: string): string | null
  /** List all keys with a prefix. */
  list(prefix: string): Array<string>
}

/**
 * Handle for an observe subscription (single-node, all-nodes
 * snapshot, or all-nodes reactive auto-subscribe). JS code SHOULD
 * `await dispose()` — D246 r3 owner-invoked detach.
 */
export declare class BenchObserveReactiveHandle {
  dispose(): Promise<void>
}

export declare class BenchOperators {
  /**
   * Build a `BenchOperators` companion that shares the supplied
   * `BenchCore`'s value registry + Core. Registrations on either
   * class are visible to the other.
   *
   * **F14 invariant (restored 2026-05-20 QA F9/m12, preserved by
   * construction):** the `binding: Arc<BenchBinding>` field and
   * the actor's Core's `BindingBoundary` upcast come from the
   * SAME `Arc<BenchBinding>` — both `core.actor_arc()` and
   * `core.binding_arc()` clone fields owned by the supplied
   * `BenchCore`. `BenchCore::new` is the single construction path
   * for that Arc; no public API mints a divergent binding.
   */
  static fromCore(core: BenchCore): BenchOperators
  /**
   * `map(src, project)` — JS callback `(handle: number) => number`
   * returns the new HandleId (typically built via
   * `BenchCore::intern_int(...)` from inside the callback).
   */
  registerMap(src: number, project: (arg: number) => number): Promise<number>
  /** `filter(src, predicate)` — JS: `(handle: number) => boolean`. */
  registerFilter(src: number, predicate: (arg: number) => boolean): Promise<number>
  /** `scan(src, seed, folder)` — JS folder: `(acc, value) => acc'`. */
  registerScan(src: number, seed: number, folder: (arg0: number, arg1: number) => number): Promise<number>
  /** `reduce(src, seed, folder)` — emit only on upstream COMPLETE. */
  registerReduce(src: number, seed: number, folder: (arg0: number, arg1: number) => number): Promise<number>
  /** `distinctUntilChanged(src)` — identity equals. */
  registerDistinctUntilChanged(src: number): Promise<number>
  /** `distinctUntilChanged(src, equals)` — custom JS equals. */
  registerDistinctUntilChangedWith(src: number, equals: (arg0: number, arg1: number) => boolean): Promise<number>
  /** `pairwise(src, packer)` — packer: `(prev, current) => HandleId`. */
  registerPairwise(src: number, packer: (arg0: number, arg1: number) => number): Promise<number>
  /** `combine(srcs, packer)` — N-ary combine with all-deps-real gate. */
  registerCombine(srcs: Array<number>, packer: (arg: Array<number>) => number): Promise<number>
  /** `withLatestFrom(primary, secondary, packer)` — fire-on-primary. */
  registerWithLatestFrom(primary: number, secondary: number, packer: (arg: Array<number>) => number): Promise<number>
  /** `merge(srcs)` — no callbacks; emit-as-arrives. */
  registerMerge(srcs: Array<number>): Promise<number>
  registerTake(src: number, count: number): Promise<number>
  registerSkip(src: number, count: number): Promise<number>
  registerTakeWhile(src: number, predicate: (arg: number) => boolean): Promise<number>
  registerLast(src: number): Promise<number>
  registerLastWithDefault(src: number, defaultHandle: number): Promise<number>
  registerFirst(src: number): Promise<number>
  registerFind(src: number, predicate: (arg: number) => boolean): Promise<number>
  registerElementAt(src: number, index: number): Promise<number>
  registerZip(srcs: Array<number>, packer: (arg: Array<number>) => number): Promise<number>
  registerConcat(first: number, second: number): Promise<number>
  registerRace(srcs: Array<number>): Promise<number>
  registerTakeUntil(src: number, notifier: number): Promise<number>
  registerSwitchMap(outer: number, project: (arg: number) => number): Promise<number>
  registerExhaustMap(outer: number, project: (arg: number) => number): Promise<number>
  registerConcatMap(outer: number, project: (arg: number) => number): Promise<number>
  /** `merge_map(outer, project, concurrency?)` — `None` = unbounded. */
  registerMergeMap(outer: number, project: (arg: number) => number, concurrency?: number | undefined | null): Promise<number>
  /** `tap(src, fn)` — side-effect on each DATA. JS callback: `(handle: u32) => void`. */
  registerTap(src: number, callback: (arg: number) => void): Promise<number>
  /** `tap_observer(src, data_fn?, error_fn?, complete_fn?)` — lifecycle-aware taps. */
  registerTapObserver(src: number, dataCallback?: ((arg: number) => void) | undefined | null, errorCallback?: ((arg: number) => void) | undefined | null, completeCallback?: (() => void) | undefined | null): Promise<number>
  /** `on_first_data(src, fn)` — one-shot side-effect on first DATA. */
  registerOnFirstData(src: number, callback: (arg: number) => void): Promise<number>
  /**
   * `rescue(src, fn)` — error recovery. JS callback: `(handle: u32) => number | -1`.
   * Returns a handle for the recovered value, or -1 to propagate the original error.
   */
  registerRescue(src: number, callback: (arg: number) => number): Promise<number>
  /**
   * `valve(src, control, gate_fn)` — boolean-gated passthrough.
   * JS gate callback: `(handle: u32) => boolean`.
   */
  registerValve(src: number, controlNode: number, gate: (arg: number) => boolean): Promise<number>
  /** `settle(src, quiet_waves, max_waves?)` — convergence detector. */
  registerSettle(src: number, quietWaves: number, maxWaves?: number | undefined | null): Promise<number>
  /** `repeat(src, count)` — sequential resubscribe loop. */
  registerRepeat(src: number, count: number): Promise<number>
  /** `buffer(src, notifier, packer)` — notifier-triggered flush. */
  registerBuffer(src: number, notifier: number, packer: (arg: Array<number>) => number): Promise<number>
  /** `buffer_count(src, count, packer)` — fixed-size buffer. */
  registerBufferCount(src: number, count: number, packer: (arg: Array<number>) => number): Promise<number>
  /** `window(src, notifier)` — notifier-triggered sub-node splitting. */
  registerWindow(src: number, notifier: number): Promise<number>
  /** `window_count(src, count)` — count-based sub-node splitting. */
  registerWindowCount(src: number, count: number): Promise<number>
  /** `timeout(src, ms, error_handle)` — idle watchdog. */
  registerTimeout(src: number, ms: number, errorHandle: number): Promise<number>
  /** `buffer_time(src, ms, packer)` — time-windowed buffer flush. */
  registerBufferTime(src: number, ms: number, packer: (arg: Array<number>) => number): Promise<number>
  /** `window_time(src, ms)` — time-windowed sub-node splitting. */
  registerWindowTime(src: number, ms: number): Promise<number>
  /** `from_iter(handles)` — emit each handle as DATA, then COMPLETE. */
  registerFromIter(handles: Array<number>): Promise<number>
  /** `of(handles)` — convenience alias for `from_iter`. */
  registerOf(handles: Array<number>): Promise<number>
  /** `empty()` — COMPLETE immediately. */
  registerEmpty(): Promise<number>
  /** `never()` — no-op, stays active. */
  registerNever(): Promise<number>
  /** `throw_error(error_handle)` — emit ERROR immediately. */
  registerThrowError(errorHandle: number): Promise<number>
  /**
   * `stratify_branch(src, rules, classifier)` — single classifier-
   * routing branch. JS classifier callback:
   * `(rules_handle: u32, value_handle: u32) => boolean`. The TS
   * `stratify(name, source, rules, opts) -> Graph` factory composes
   * N instances of this one per rule.
   */
  registerStratifyBranch(src: number, rulesNode: number, classifier: (arg0: number, arg1: number) => boolean): Promise<number>
}

export declare class BenchReactiveIndex {
  /**
   * **`run_sync` safety:** see [`BenchReactiveLog::create`]'s doc
   * — `ReactiveIndex::new` is a topology mutation safe under
   * `run_sync` *only* because no subscribers exist for the
   * freshly-created node (lifecycle precondition).
   */
  static create(core: BenchCore, packer: (arg: Array<number>) => number): BenchReactiveIndex
  get nodeId(): number
  get size(): number
  has(primary: number): boolean
  get(primary: number): number
  upsert(primary: number, secondary: string, value: number, numericKey?: number | undefined | null): Promise<boolean>
  delete(primary: number, numericKey?: number | undefined | null): Promise<void>
  /** F20/D205: values whose numeric primary sorts within `[start, end)`. */
  rangeByPrimary(start: number, end: number): Array<number>
  clear(): Promise<void>
}

export declare class BenchReactiveList {
  /**
   * **`run_sync` safety:** see [`BenchReactiveLog::create`]'s doc
   * — `ReactiveList::new` is a topology mutation safe under
   * `run_sync` *only* because no subscribers exist for the
   * freshly-created node (lifecycle precondition).
   */
  static create(core: BenchCore, packer: (arg: Array<number>) => number): BenchReactiveList
  get nodeId(): number
  get size(): number
  append(handle: number): Promise<void>
  appendMany(handles: Array<number>): Promise<void>
  insert(index: number, handle: number): Promise<void>
  pop(index?: number | undefined | null): Promise<number>
  clear(): Promise<void>
  at(index: number): number
}

export declare class BenchReactiveLog {
  /**
   * Create from a BenchCore + packer callback. Constructor runs
   * `ReactiveLog::new(&core, …)` on the actor's worker thread via
   * `run_sync` (briefly blocks libuv on the one-shot factory call).
   *
   * **`run_sync` safety, lifecycle-precondition framing
   * (QA 2026-05-20 F7):** `ReactiveLog::new` is a Core *topology
   * mutation* (`core.register_state(...)`), not a read-only op.
   * It is safe under `run_sync` because **no subscribers exist
   * yet for this newly-created node** — no TSFN-backed sink can
   * fire during construction → no `bridge_sync` libuv-busy
   * hazard. The invariant is the *lifecycle precondition* (the
   * node is freshly created, no `subscribe` could have been
   * called yet), NOT the substrate operation being side-effect-
   * free. A future change that wires construction-time
   * subscribers would invalidate this analysis.
   */
  static create(core: BenchCore, packer: (arg: Array<number>) => number, maxSize?: number | undefined | null): BenchReactiveLog
  get nodeId(): number
  get size(): number
  append(handle: number): Promise<void>
  appendMany(handles: Array<number>): Promise<void>
  clear(): Promise<void>
  at(index: number): number
  trimHead(n: number): Promise<void>
  viewTail(packer: (arg: Array<number>) => number, n: number): Promise<BenchLogView>
  viewSlice(packer: (arg: Array<number>) => number, start: number, stop?: number | undefined | null): Promise<BenchLogView>
  viewFromCursor(packer: (arg: Array<number>) => number, cursorNodeId: number, readCursor: (arg: Array<number>) => number): Promise<BenchLogView>
  scan(seed: number, folder: (arg: Array<number>) => number): Promise<BenchScanHandle>
  attach(upstreamNodeId: number): Promise<BenchLogSubscription>
}

export declare class BenchReactiveMap {
  /**
   * **`run_sync` safety:** see [`BenchReactiveLog::create`]'s doc
   * — `ReactiveMap::new` is a topology mutation safe under
   * `run_sync` *only* because no subscribers exist for the
   * freshly-created node (lifecycle precondition).
   */
  static create(core: BenchCore, packer: (arg: Array<number>) => number, maxSize?: number | undefined | null, defaultTtl?: number | undefined | null): BenchReactiveMap
  get nodeId(): number
  get size(): number
  /**
   * `async fn` at the napi boundary (QA fix 2026-05-20, Edge Case
   * Hunter F3 / Blind Hunter C2): `ReactiveMap::has` is NOT
   * read-only — when TTL is configured, an expired-key check
   * triggers `prune_expired_inner` + `self.emitter.emit(core,
   * snapshot)` (see `crates/graphrefly-structures/src/reactive.rs`
   * `has` body). The emission fires subscribers; if any subscriber
   * uses `bridge_sync` (Blocking TSFN call), libuv must be free to
   * pump the TSFN microtask — under the prior sync `run_sync`
   * shape libuv was blocked on the actor reply → 3-way deadlock.
   * `actor.run` keeps libuv free during the await.
   *
   * **Public-API change:** `Impl.ImplReactiveMap.has(key)` is
   * `Promise<boolean>` (was `boolean`); `parity-tests/impls/
   * types.ts` widened correspondingly. See cross-track-ledger.md
   * §1 row 2026-05-20 (F3).
   */
  has(key: number): Promise<boolean>
  /**
   * `async fn` at the napi boundary — same rationale as `has`
   * (TTL-prune side-effect emits a snapshot, can deadlock libuv
   * under sync `run_sync`).
   */
  get(key: number): Promise<number>
  set(key: number, value: number, ttl?: number | undefined | null): Promise<void>
  delete(key: number): Promise<void>
  clear(): Promise<void>
}

export declare class BenchScanHandle {
  get nodeId(): number
}

/**
 * JS-facing handle for storage detach. Stores `Arc<CoreActor>` +
 * `handle_key: u64` keying into the actor's `WORKER_EXTRAS`.
 * `StorageHandle` is `!Send` (holds a `Rc<RefCell<GraphInner>>`
 * via its `GraphObserveAllReactive` field) so it lives on the
 * worker thread; `dispose()` posts a `take_extra` + `detach(core)`
 * closure through the actor.
 */
export declare class BenchStorageHandle {
  /**
   * Explicitly dispose (full owner-invoked teardown). Idempotent
   * — second call finds no entry in `WORKER_EXTRAS` and no-ops.
   */
  dispose(): Promise<void>
}

export declare class BenchValueAppendLogTier {
  static create(backend: BenchMemoryBackend, name?: string | undefined | null, compactEvery?: number | undefined | null, debounceMs?: number | undefined | null): BenchValueAppendLogTier
  /** Append entries (JSON array). */
  appendEntries(entriesJson: string): void
  /** Load all entries (returns JSON array). */
  loadEntries(keyFilter?: string | undefined | null): string
  flush(): void
  rollback(): void
  get name(): string
}

export declare class BenchValueKvTier {
  static create(backend: BenchMemoryBackend, name?: string | undefined | null, compactEvery?: number | undefined | null, debounceMs?: number | undefined | null): BenchValueKvTier
  save(key: string, valueJson: string): void
  load(key: string): string | null
  delete(key: string): void
  list(prefix: string): Array<string>
  flush(): void
  rollback(): void
  get name(): string
}

export declare class BenchValueSnapshotTier {
  static create(backend: BenchMemoryBackend, name?: string | undefined | null, compactEvery?: number | undefined | null, debounceMs?: number | undefined | null): BenchValueSnapshotTier
  save(valueJson: string): void
  load(): string | null
  flush(): void
  rollback(): void
  get name(): string
  get debounceMs(): number | null
  get compactEvery(): number | null
}

export declare class BenchWalKvTier {
  static create(backend: BenchMemoryBackend, name?: string | undefined | null, compactEvery?: number | undefined | null): BenchWalKvTier
  /** Save a WAL frame (JSON) under the given key. */
  save(key: string, frameJson: string): void
  /** Load a WAL frame by key (JSON or null). */
  load(key: string): string | null
  delete(key: string): void
  /** List keys under a prefix. */
  list(prefix: string): Array<string>
  flush(): void
  rollback(): void
  get name(): string
}

export interface BatchEmissionJs {
  kind: string
  value?: number
}

/** WAL frame sequence padding width (20). */
export const BENCH_WAL_FRAME_SEQ_PAD: number

/** Attach snapshot storage to a graph. Returns a disposable handle. */
export declare function benchAttachSnapshotStorage(graph: BenchGraph, snapshotTier: BenchCheckpointSnapshotTier, walTier?: BenchWalKvTier | undefined | null): Promise<BenchStorageHandle>

/** Take a graph snapshot (JSON-serialized `GraphPersistSnapshot`). */
export declare function benchGraphSnapshot(graph: BenchGraph): Promise<string>

/** Lifecycle replay order: `["spec", "data", "ownership"]`. */
export declare function benchReplayOrder(): Array<string>

/**
 * Restore graph state from snapshot + WAL tiers.
 * Returns a JSON-serialized `RestoreResult`.
 */
export declare function benchRestoreSnapshot(graph: BenchGraph, snapshotTier: BenchCheckpointSnapshotTier, walTier: BenchWalKvTier, targetSeq?: number | undefined | null): Promise<string>

/** Verify a WAL frame's checksum. Returns true if valid. */
export declare function benchVerifyWalFrameChecksum(frameJson: string): boolean

/** Compute a WAL frame's checksum (SHA-256 hex). Input: WAL frame JSON. */
export declare function benchWalFrameChecksum(frameJson: string): string

/** Compute the storage key for a WAL frame: `<prefix>/wal/<seq_padded>`. */
export declare function benchWalFrameKey(prefix: string, frameSeq: number): string

export declare const enum BuiltinBatchFn {
  MapAddOneBatch = 'MapAddOneBatch',
  MulTenThenComplete = 'MulTenThenComplete'
}

export declare const enum BuiltinFn {
  Identity = 'Identity',
  AddOne = 'AddOne'
}

export declare function globalCacheInt(nodeId: number): Promise<number>

export declare function globalEmitInt(nodeId: number, value: number): Promise<void>

export declare function globalRegisterDerivedIdentity(depIds: Array<number>): Promise<number>

export declare function globalRegisterStateInt(initial: number): Promise<number>

export declare function globalRustEmitLoop(nodeId: number, n: number): Promise<void>

export declare function globalSubscribeNoop(nodeId: number): Promise<number>

/**
 * Empty FFI round-trip. Measures pure napi-rs call overhead with no Rust work.
 * Bench: `for (let i = 0; i < N; i++) noop_call();` — divide by N for per-call cost.
 */
export declare function noopCall(): void

/**
 * FFI round-trip with one integer return. Measures napi-rs overhead with a
 * minimal payload (single i32). Real workloads always return *something* —
 * this captures the "common case" baseline that `noop_call` can't.
 */
export declare function noopCallReturningInt(): number

/**
 * JS-exposed `GraphRemoveAudit`. Mirrors `graphrefly_graph::GraphRemoveAudit`'s
 * flat counts; per-node detail isn't surfaced through the napi boundary
 * in v1 (parity scenarios only assert counts).
 */
export interface RemoveAuditJs {
  nodeCount: number
  mountCount: number
}

/** JS-exposed mirror of [`graphrefly_core::ResumeReport`]. */
export interface ResumeReportJs {
  replayed: number
  dropped: number
}

/** Smoke export — verifies napi-rs link works. */
export declare function version(): string
