/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BenchCheckpointSnapshotTier {
  static create(backend: BenchMemoryBackend, name?: string | undefined | null, compactEvery?: number | undefined | null): BenchCheckpointSnapshotTier
  /** Save a checkpoint record (JSON). */
  save(recordJson: string): void
  /** Load the latest checkpoint record (JSON or null). */
  load(): string | null
  flush(): void
  rollback(): void
  get name(): string
}

export declare class BenchCore {
  /** Construct a fresh `BenchCore` wired to a Rust-side value registry. */
  constructor()
  /**
   * Intern an i32 value; returns its HandleId. Used by JS-side
   * adapters to construct fresh handles for operator callback returns
   * (e.g., `register_map(src, x => intern_int(deref_int(x) + 1))`).
   */
  internInt(value: number): number
  /**
   * Dereference a HandleId to its i32 payload. Returns -1 for
   * unknown handles or non-Int values (matches `cache_int`'s
   * sentinel convention for the bench surface).
   */
  derefInt(handle: number): number
  /**
   * Allocate a fresh handle for the JS adapter to associate with a
   * JS-side value (D073). Returns the handle ID; refcount=1.
   * **Caller responsibility:** the JS adapter MUST register the
   * value in its mirror map BEFORE handing the handle to anything
   * that may dereference it (operator callbacks, sinks).
   * Sync — pure Registry op, no Core wave.
   */
  allocExternalHandle(): number
  /**
   * Register a state node initialized with a JS-allocated handle.
   * JS adapter must have called `alloc_external_handle` and stored
   * the value in its mirror first. The handle's refcount=1 share is
   * consumed by the state node's initial cache slot.
   */
  registerStateWithHandle(initialHandle: number): Promise<number>
  /**
   * Emit a JS-allocated handle on a node. JS adapter must have
   * stored the value in its mirror first. The handle's refcount
   * share is consumed by Core's emission path (Core retains the
   * handle into the cache slot).
   */
  emitHandle(nodeId: number, handle: number): Promise<void>
  /**
   * Read a node's current cache as a HandleId. Returns 0
   * (NO_HANDLE) for sentinel cache. JS adapter looks up the handle
   * in its mirror map.
   */
  cacheHandle(nodeId: number): Promise<number>
  /** Register a state node with an i32 initial value. */
  registerStateInt(initial: number): Promise<number>
  /** Register a state node with sentinel cache (no initial value). */
  registerStateSentinel(): Promise<number>
  /** Register a derived node with a built-in fn shape. */
  registerDerived(depIds: Array<number>, builtin: BuiltinFn): Promise<number>
  /**
   * Subscribe a noop sink. Activation may fire fns (including
   * JS-callback operators), so this MUST be async.
   */
  subscribeNoop(nodeId: number): Promise<number>
  /**
   * Subscribe with a JS callback sink (D077). The callback receives
   * a flat-encoded `Vec<u32>` per message batch — alternating
   * `(variantCode, payload)` pairs. JS adapter decodes via the
   * `MSG_CODE_*` table (mirrored in `rust.ts`) and dereferences
   * payload handles via the JS-side mirror map.
   *
   * **Sync-bridge semantics:** the returned Promise resolves AFTER
   * the subscribe-time handshake fires AND the JS sink callback
   * completes (per `bridge_sync_unit` blocking the tokio thread on
   * a sync_channel until JS responds via libuv pump). JS code
   * MUST `await` this method — synchronous calling deadlocks.
   *
   * `pub fn` (not `async fn`) because `Function<>` is `!Send`; the
   * async work runs inside `env.spawn_future(async move { ... })`.
   */
  subscribeWithTsfn(nodeId: number, sinkCallback: (arg: Array<number>) => void): Promise<number>
  /**
   * Install the JS-side prune callback (D076). Called once at JS
   * adapter construction. Subsequent calls overwrite. The callback
   * receives a single `(handle: u32)` and should `Map.delete(handle)`
   * in the JS-side mirror. Fired NON-BLOCKING from
   * `BindingBoundary::release_handle`.
   */
  setReleaseCallback(callback: (arg: number) => void): void
  /**
   * Drop the subscription at `idx` (releases activation refcount).
   * Async because Subscription's Drop locks Core's mutex; running
   * on a tokio blocking thread keeps the JS thread free during any
   * terminal-cascade work the unsubscribe triggers.
   */
  unsubscribe(idx: number): Promise<void>
  /**
   * Drain all retained subscriptions on a tokio blocking thread —
   * JS code MUST `await core.dispose()` before letting `BenchCore`
   * drop. Closes the BenchCore::Drop deadlock vector (Slice Y):
   * without `dispose`, GC of the napi instance runs `Drop` on the
   * JS thread; each `Subscription::Drop` blocks on `Core`'s mutex;
   * if a tokio blocking-pool thread is mid-wave (parked in a TSFN
   * bridge waiting for libuv to pump a JS-callback result), the JS
   * thread waiting for the mutex stalls libuv → TSFN never
   * delivers → tokio thread blocks forever. Calling `dispose` first
   * ships the subscription drop work onto a tokio blocking thread
   * (which is allowed to block on the mutex while the JS thread
   * stays free to pump libuv).
   *
   * Idempotent: subsequent calls are no-ops once the vec is drained.
   */
  dispose(): Promise<void>
  /** Emit an i32 value on a state node. */
  emitInt(nodeId: number, value: number): Promise<void>
  /** Read a state node's current cache as i32. */
  cacheInt(nodeId: number): Promise<number>
  /** Tight loop: emit `n` times on a state node, no JS call between. */
  rustEmitLoop(nodeId: number, n: number): Promise<void>
  allocLockId(): Promise<number>
  setPauseBufferCap(cap?: number | undefined | null): Promise<void>
  pause(nodeId: number, lockId: number): Promise<void>
  resume(nodeId: number, lockId: number): Promise<ResumeReportJs | null>
  isPaused(nodeId: number): Promise<boolean>
  /**
   * Number of pause locks currently held. Returns Err on overflow
   * instead of saturating silently (M8 fix — matches `alloc_lock_id`).
   */
  pauseLockCount(nodeId: number): Promise<number>
  holdsPauseLock(nodeId: number, lockId: number): Promise<boolean>
  invalidate(nodeId: number): Promise<void>
  complete(nodeId: number): Promise<void>
  /**
   * Emit ERROR with a JS-allocated handle (D076 parity — non-i32 error
   * payloads). JS adapter must have called `alloc_external_handle` and
   * stored the value first. The handle's refcount share is consumed by
   * Core's error path.
   */
  errorHandle(nodeId: number, handle: number): Promise<void>
  errorInt(nodeId: number, errCode: number): Promise<void>
  teardown(nodeId: number): Promise<void>
  addMetaCompanion(parent: number, companion: number): Promise<void>
  setResubscribable(nodeId: number, resubscribable: boolean): Promise<void>
  batchEmitInts(nodeId: number, values: Array<number>): Promise<void>
  setDeps(nodeId: number, newDepIds: Array<number>): Promise<void>
  hasFiredOnce(nodeId: number): Promise<boolean>
  /**
   * Register a derived node whose fn returns `FnResult::Batch`.
   * R1.3.6.b — multi-emit per fire flows in same wave.
   */
  registerBatchDerived(depIds: Array<number>, builtin: BuiltinBatchFn): Promise<number>
  /**
   * Batch-dispatch a handle-encoded message sequence atomically (Phase E
   * /qa F2 — D077 "one call = one wave"). The `encoded` argument is a
   * flat `[code_0, payload_0, code_1, payload_1, ...]` array using the
   * same `MSG_CODE_*` table that `subscribe_with_tsfn` decodes — so
   * `RustNode.down(msgs)` can encode once on the JS side and replay
   * the whole batch through one Core wave.
   *
   * Codes accepted:
   * - 1 (DIRTY) — Core auto-emits DIRTY before tier-3 emissions; an
   *   explicit DIRTY in `encoded` is a no-op (matches legacy semantics).
   * - 3 (DATA) — payload is a JS-allocated handle (D073).
   * - 4 (INVALIDATE) — no payload.
   * - 5 (PAUSE) — payload is a lock id.
   * - 6 (RESUME) — payload is a lock id.
   * - 7 (COMPLETE) — no payload.
   * - 8 (ERROR) — payload is a JS-allocated handle.
   * - 9 (TEARDOWN) — no payload.
   *
   * Codes 0 (Start), 2 (Resolved) are not accepted on the down-path
   * (legacy parity — Start is per-subscription, Resolved is generated
   * by Core's equals path).
   */
  batchEmitHandleMessages(nodeId: number, encoded: Array<number>): Promise<void>
  batchEmitMessages(nodeId: number, msgs: Array<BatchEmissionJs>): Promise<void>
}

/**
 * RAII handle for a reactive describe subscription. JS code SHOULD
 * `await dispose()` before letting it drop — that path runs the
 * unsubscribe on a tokio blocking thread, keeping the JS thread free
 * to pump libuv. As defense-in-depth (Slice X3 /qa A), the `Drop`
 * impl ALSO ships the inner-drop to a tokio blocking thread
 * fire-and-forget, so a forgotten `dispose()` doesn't deadlock the
 * JS thread on Graph's namespace_sinks mutex.
 */
export declare class BenchDescribeReactiveHandle {
  /**
   * Drop the inner subscription on a tokio blocking thread.
   * Idempotent — subsequent calls are no-ops.
   */
  dispose(): Promise<void>
}

/**
 * JS-facing wrapper around a `graphrefly_graph::Graph`. Each
 * `BenchGraph` shares its `BenchCore`'s value registry + binding so
 * nodes registered through `BenchGraph::state(...)` are visible to
 * `BenchOperators::register_*(...)` and vice-versa.
 *
 * **`binding` field redundancy** (Slice X3 / Phase E /qa F14): the
 * `binding: Arc<BenchBinding>` field carries the same allocation as
 * `core.binding: Arc<dyn BindingBoundary>` — they're upcasts of the
 * same `Arc<BenchBinding>`. The typed field is retained because
 * `BenchGraph::derived` needs the concrete `BenchBinding` to access
 * `binding.registry.lock()` for fn registration; recovering the
 * concrete type from the trait-erased `core.binding` would require
 * `Arc::downcast` (not available on `dyn Trait` without `Any` bound).
 * `from_core` enforces the invariant via a debug-build pointer-equality
 * assert so the field can't drift from `core`'s view.
 */
export declare class BenchGraph {
  /**
   * Construct a fresh root graph wired to a `BenchCore`'s binding +
   * Core (D074). The BenchGraph SHARES the BenchCore's Core via
   * `Graph::with_existing_core` (added in this slice to graphrefly-
   * graph), so nodes registered through `BenchGraph::state(...)`
   * are visible to operator factories on the same `BenchCore`.
   */
  static fromCore(core: BenchCore, name: string): BenchGraph
  name(): string
  nodeCount(): number
  nodeNames(): Array<string>
  childNames(): Array<string>
  isDestroyed(): boolean
  /** Resolve a path to a NodeId; returns 0 (NO_NODE) if missing. */
  tryResolve(path: string): number
  /**
   * Reverse lookup: returns the local name for a NodeId, or None
   * if unnamed in this graph.
   */
  nameOf(nodeId: number): string | null
  /**
   * `state(name, initial_handle?)`. `None` → sentinel cache.
   * Caller (JS adapter) holds the handle's refcount via
   * `BenchCore::alloc_external_handle`; ownership transfers here.
   */
  state(name: string, initialHandle?: number | undefined | null): Promise<number>
  /**
   * `derived(name, deps, builtin)` — uses a built-in fn from
   * `BuiltinFn` (Identity / AddOne) since we don't take JS callbacks
   * here. For real JS-callback derived nodes, callers go through
   * `BenchOperators` operators (map/filter/etc.) and `add(name, id)`
   * the resulting NodeId.
   */
  derived(name: string, depIds: Array<number>, builtin: BuiltinFn): Promise<number>
  /**
   * Register an existing node (e.g., from `BenchOperators::register_map`)
   * under `name` in this graph's namespace.
   */
  add(name: string, nodeId: number): number
  setByName(name: string, handle: number): Promise<void>
  getByName(name: string): Promise<number>
  invalidateByName(name: string): Promise<void>
  completeByName(name: string): Promise<void>
  errorByName(name: string, errorHandle: number): Promise<void>
  remove(name: string): Promise<RemoveAuditJs>
  signalInvalidate(): Promise<void>
  signalPause(lockId: number): Promise<void>
  signalResume(lockId: number): Promise<void>
  /**
   * Atomic-ish signal broadcast over a flat (code, payload) batch
   * (Phase E /qa F3 — D077 server-side input validation). Accepts
   * the same `MSG_CODE_*` table as `batch_emit_handle_messages`,
   * but rejects everything except INVALIDATE / PAUSE / RESUME — the
   * only kinds canonical §3.7.1 supports for graph-wide broadcast.
   * DATA / RESOLVED / COMPLETE / ERROR / TEARDOWN return a typed
   * `napi::Error` BEFORE any signal fires (legacy parity:
   * `g.signal([[DATA, ...]])` throws synchronously).
   */
  signalBatch(encoded: Array<number>): Promise<void>
  /**
   * Mount a fresh empty subgraph under `name`; returns a new
   * `BenchGraph` sharing this graph's Core/binding/registry.
   */
  mountNew(name: string): Promise<BenchGraph>
  /** Detach a previously-mounted subgraph by name. */
  unmount(name: string): Promise<RemoveAuditJs>
  destroy(): Promise<void>
  /**
   * Static edges snapshot — `Vec<(from_name, to_name)>` flattened to
   * alternating `Vec<String>` for napi marshaling.
   */
  edges(recursive: boolean): Array<string>
  /**
   * JSON-serialized describe snapshot. JS adapter parses with
   * `JSON.parse`. Static — for reactive describe, see follow-on
   * slice (out of scope per D074).
   */
  describeJson(): string
  /**
   * Subscribe to live topology snapshots (canonical R3.6.1
   * `describe({ reactive: true })`). The JS callback receives a
   * JSON-serialized [`graphrefly_graph::GraphDescribeOutput`] on
   * each fire; first fire is the push-on-subscribe initial
   * snapshot, subsequent fires are post-change snapshots.
   *
   * Returns a [`BenchDescribeReactiveHandle`] napi class. JS code
   * MUST `await handle.dispose()` before letting the handle drop —
   * the unsubscribe runs on a tokio blocking thread to avoid the
   * JS-thread / Core-mutex deadlock vector that `BenchCore::dispose`
   * closes for subscriptions.
   */
  describeReactive(sink: (arg: string) => void): Promise<BenchDescribeReactiveHandle>
  /**
   * Subscribe to all-named-nodes message stream with auto-subscribe
   * on late-added nodes (canonical R3.6.2 `observe(undefined, {
   * reactive: true })`). The JS callback receives `(name,
   * encoded_msgs)` per emission — `encoded_msgs` is the same flat
   * `[code_0, payload_0, ...]` shape that `subscribe_with_tsfn`
   * uses, decoded JS-side via the `MSG_CODE_*` table.
   *
   * Returns a [`BenchObserveReactiveHandle`] napi class.
   * `await handle.dispose()` unsubscribes everything (the inner
   * `GraphObserveAllReactive` clears all fan-out subs + the
   * namespace-change listener).
   */
  observeAllReactive(sink: (arg0: string, arg1: Array<number>) => void): Promise<BenchObserveReactiveHandle>
  /**
   * Sink-style observe of a single node (canonical R3.6.2 default
   * mode `observe(path)`). Returns a subscription index into a
   * `BenchObserveReactiveHandle` slot that mirrors `BenchCore`'s
   * subscriptions vec semantics. Provided for canonical-spec
   * completeness — most parity scenarios use the reactive variant.
   *
   * `path` resolves via `Graph::node(path)`; panics if unknown.
   */
  observeSubscribe(path: string | undefined | null, sink: (arg0: string, arg1: Array<number>) => void): Promise<BenchObserveReactiveHandle>
}

/** In-memory storage backend shared across tiers. */
export declare class BenchMemoryBackend {
  constructor()
  /** Read raw bytes for a key (JSON string or null). */
  readRaw(key: string): string | null
  /** List all keys with a prefix. */
  list(prefix: string): Array<string>
}

/**
 * RAII handle for an observe subscription (single-node, all-nodes
 * snapshot, or all-nodes reactive auto-subscribe). JS code SHOULD
 * `await dispose()` (runs unsubscribe on tokio); as defense-in-depth
 * (Slice X3 /qa A) the `Drop` impl ALSO ships the inner drop to
 * tokio fire-and-forget so a forgotten `dispose()` doesn't deadlock
 * the JS thread on Core's mutex via `Subscription::Drop`.
 */
export declare class BenchObserveReactiveHandle {
  dispose(): Promise<void>
}

export declare class BenchOperators {
  /**
   * Build a `BenchOperators` companion that shares the supplied
   * `BenchCore`'s value registry + Core. Registrations on either
   * class are visible to the other.
   */
  static fromCore(core: BenchCore): BenchOperators
  /**
   * `map(src, project)` — JS callback `(handle: number) => number`
   * returns the new HandleId (typically built via
   * `BenchCore::intern_int(...)` from inside the callback).
   */
  registerMap(src: number, project: (arg: number) => number): Promise<number>
  /** `filter(src, predicate)` — JS: `(handle: number) => boolean`. */
  registerFilter(src: number, predicate: (arg: number) => boolean): Promise<number>
  /** `scan(src, seed, folder)` — JS folder: `(acc, value) => acc'`. */
  registerScan(src: number, seed: number, folder: (arg0: number, arg1: number) => number): Promise<number>
  /** `reduce(src, seed, folder)` — emit only on upstream COMPLETE. */
  registerReduce(src: number, seed: number, folder: (arg0: number, arg1: number) => number): Promise<number>
  /** `distinctUntilChanged(src)` — identity equals. */
  registerDistinctUntilChanged(src: number): Promise<number>
  /** `distinctUntilChanged(src, equals)` — custom JS equals. */
  registerDistinctUntilChangedWith(src: number, equals: (arg0: number, arg1: number) => boolean): Promise<number>
  /** `pairwise(src, packer)` — packer: `(prev, current) => HandleId`. */
  registerPairwise(src: number, packer: (arg0: number, arg1: number) => number): Promise<number>
  /** `combine(srcs, packer)` — N-ary combine with all-deps-real gate. */
  registerCombine(srcs: Array<number>, packer: (arg: Array<number>) => number): Promise<number>
  /** `withLatestFrom(primary, secondary, packer)` — fire-on-primary. */
  registerWithLatestFrom(primary: number, secondary: number, packer: (arg: Array<number>) => number): Promise<number>
  /** `merge(srcs)` — no callbacks; emit-as-arrives. */
  registerMerge(srcs: Array<number>): Promise<number>
  registerTake(src: number, count: number): Promise<number>
  registerSkip(src: number, count: number): Promise<number>
  registerTakeWhile(src: number, predicate: (arg: number) => boolean): Promise<number>
  registerLast(src: number): Promise<number>
  registerLastWithDefault(src: number, defaultHandle: number): Promise<number>
  registerFirst(src: number): Promise<number>
  registerFind(src: number, predicate: (arg: number) => boolean): Promise<number>
  registerElementAt(src: number, index: number): Promise<number>
  registerZip(srcs: Array<number>, packer: (arg: Array<number>) => number): Promise<number>
  registerConcat(first: number, second: number): Promise<number>
  registerRace(srcs: Array<number>): Promise<number>
  registerTakeUntil(src: number, notifier: number): Promise<number>
  registerSwitchMap(outer: number, project: (arg: number) => number): Promise<number>
  registerExhaustMap(outer: number, project: (arg: number) => number): Promise<number>
  registerConcatMap(outer: number, project: (arg: number) => number): Promise<number>
  /** `merge_map(outer, project, concurrency?)` — `None` = unbounded. */
  registerMergeMap(outer: number, project: (arg: number) => number, concurrency?: number | undefined | null): Promise<number>
  /** `tap(src, fn)` — side-effect on each DATA. JS callback: `(handle: u32) => void`. */
  registerTap(src: number, callback: (arg: number) => void): Promise<number>
  /** `tap_observer(src, data_fn?, error_fn?, complete_fn?)` — lifecycle-aware taps. */
  registerTapObserver(src: number, dataCallback?: ((arg: number) => void) | undefined | null, errorCallback?: ((arg: number) => void) | undefined | null, completeCallback?: (() => void) | undefined | null): Promise<number>
  /** `on_first_data(src, fn)` — one-shot side-effect on first DATA. */
  registerOnFirstData(src: number, callback: (arg: number) => void): Promise<number>
  /**
   * `rescue(src, fn)` — error recovery. JS callback: `(handle: u32) => number | -1`.
   * Returns a handle for the recovered value, or -1 to propagate the original error.
   */
  registerRescue(src: number, callback: (arg: number) => number): Promise<number>
  /**
   * `valve(src, control, gate_fn)` — boolean-gated passthrough.
   * JS gate callback: `(handle: u32) => boolean`.
   */
  registerValve(src: number, controlNode: number, gate: (arg: number) => boolean): Promise<number>
  /** `settle(src, quiet_waves, max_waves?)` — convergence detector. */
  registerSettle(src: number, quietWaves: number, maxWaves?: number | undefined | null): Promise<number>
  /** `repeat(src, count)` — sequential resubscribe loop. */
  registerRepeat(src: number, count: number): Promise<number>
  /** `buffer(src, notifier, packer)` — notifier-triggered flush. */
  registerBuffer(src: number, notifier: number, packer: (arg: Array<number>) => number): Promise<number>
  /** `buffer_count(src, count, packer)` — fixed-size buffer. */
  registerBufferCount(src: number, count: number, packer: (arg: Array<number>) => number): Promise<number>
  /** `window(src, notifier)` — notifier-triggered sub-node splitting. */
  registerWindow(src: number, notifier: number): Promise<number>
  /** `window_count(src, count)` — count-based sub-node splitting. */
  registerWindowCount(src: number, count: number): Promise<number>
  /** `timeout(src, ms, error_handle)` — idle watchdog. */
  registerTimeout(src: number, ms: number, errorHandle: number): Promise<number>
  /** `buffer_time(src, ms, packer)` — time-windowed buffer flush. */
  registerBufferTime(src: number, ms: number, packer: (arg: Array<number>) => number): Promise<number>
  /** `window_time(src, ms)` — time-windowed sub-node splitting. */
  registerWindowTime(src: number, ms: number): Promise<number>
  /** `from_iter(handles)` — emit each handle as DATA, then COMPLETE. */
  registerFromIter(handles: Array<number>): Promise<number>
  /** `of(handles)` — convenience alias for `from_iter`. */
  registerOf(handles: Array<number>): Promise<number>
  /** `empty()` — COMPLETE immediately. */
  registerEmpty(): Promise<number>
  /** `never()` — no-op, stays active. */
  registerNever(): Promise<number>
  /** `throw_error(error_handle)` — emit ERROR immediately. */
  registerThrowError(errorHandle: number): Promise<number>
  /**
   * `stratify_branch(src, rules, classifier)` — single classifier-
   * routing branch. JS classifier callback:
   * `(rules_handle: u32, value_handle: u32) => boolean`. The TS
   * `stratify(name, source, rules, opts) -> Graph` factory composes
   * N instances of this one per rule.
   */
  registerStratifyBranch(src: number, rulesNode: number, classifier: (arg0: number, arg1: number) => boolean): Promise<number>
}

export declare class BenchReactiveIndex {
  static create(core: BenchCore, packer: (arg: Array<number>) => number): BenchReactiveIndex
  get nodeId(): number
  get size(): number
  has(primary: number): boolean
  get(primary: number): number
  /** `secondary` is a sort-key string (not a handle). */
  upsert(primary: number, secondary: string, value: number): Promise<boolean>
  delete(primary: number): Promise<void>
  clear(): Promise<void>
}

export declare class BenchReactiveList {
  static create(core: BenchCore, packer: (arg: Array<number>) => number): BenchReactiveList
  get nodeId(): number
  get size(): number
  append(handle: number): Promise<void>
  appendMany(handles: Array<number>): Promise<void>
  insert(index: number, handle: number): Promise<void>
  pop(index?: number | undefined | null): Promise<number>
  clear(): Promise<void>
  at(index: number): number
}

export declare class BenchReactiveLog {
  /**
   * Create from a BenchCore + packer callback. Sync factory — lightweight
   * Core mutex operation (same risk profile as BenchOperators::from_core).
   */
  static create(core: BenchCore, packer: (arg: Array<number>) => number, maxSize?: number | undefined | null): BenchReactiveLog
  get nodeId(): number
  get size(): number
  append(handle: number): Promise<void>
  appendMany(handles: Array<number>): Promise<void>
  clear(): Promise<void>
  at(index: number): number
  trimHead(n: number): Promise<void>
}

export declare class BenchReactiveMap {
  static create(core: BenchCore, packer: (arg: Array<number>) => number, maxSize?: number | undefined | null, defaultTtl?: number | undefined | null): BenchReactiveMap
  get nodeId(): number
  get size(): number
  has(key: number): boolean
  get(key: number): number
  set(key: number, value: number, ttl?: number | undefined | null): Promise<void>
  delete(key: number): Promise<void>
  clear(): Promise<void>
}

export declare class BenchStorageHandle {
  /** Explicitly dispose (stop persistence, unsubscribe sinks). */
  dispose(): Promise<void>
}

export declare class BenchValueAppendLogTier {
  static create(backend: BenchMemoryBackend, name?: string | undefined | null, compactEvery?: number | undefined | null, debounceMs?: number | undefined | null): BenchValueAppendLogTier
  /** Append entries (JSON array). */
  appendEntries(entriesJson: string): void
  /** Load all entries (returns JSON array). */
  loadEntries(keyFilter?: string | undefined | null): string
  flush(): void
  rollback(): void
  get name(): string
}

export declare class BenchValueKvTier {
  static create(backend: BenchMemoryBackend, name?: string | undefined | null, compactEvery?: number | undefined | null, debounceMs?: number | undefined | null): BenchValueKvTier
  save(key: string, valueJson: string): void
  load(key: string): string | null
  delete(key: string): void
  list(prefix: string): Array<string>
  flush(): void
  rollback(): void
  get name(): string
}

export declare class BenchValueSnapshotTier {
  static create(backend: BenchMemoryBackend, name?: string | undefined | null, compactEvery?: number | undefined | null, debounceMs?: number | undefined | null): BenchValueSnapshotTier
  save(valueJson: string): void
  load(): string | null
  flush(): void
  rollback(): void
  get name(): string
  get debounceMs(): number | null
  get compactEvery(): number | null
}

export declare class BenchWalKvTier {
  static create(backend: BenchMemoryBackend, name?: string | undefined | null, compactEvery?: number | undefined | null): BenchWalKvTier
  /** Save a WAL frame (JSON) under the given key. */
  save(key: string, frameJson: string): void
  /** Load a WAL frame by key (JSON or null). */
  load(key: string): string | null
  delete(key: string): void
  /** List keys under a prefix. */
  list(prefix: string): Array<string>
  flush(): void
  rollback(): void
  get name(): string
}

export interface BatchEmissionJs {
  kind: string
  value?: number
}

/** WAL frame sequence padding width (20). */
export const BENCH_WAL_FRAME_SEQ_PAD: number

/** Attach snapshot storage to a graph. Returns a disposable handle. */
export declare function benchAttachSnapshotStorage(graph: BenchGraph, snapshotTier: BenchCheckpointSnapshotTier, walTier?: BenchWalKvTier | undefined | null): Promise<BenchStorageHandle>

/** Take a graph snapshot (JSON-serialized `GraphPersistSnapshot`). */
export declare function benchGraphSnapshot(graph: BenchGraph): Promise<string>

/** Lifecycle replay order: `["spec", "data", "ownership"]`. */
export declare function benchReplayOrder(): Array<string>

/**
 * Restore graph state from snapshot + WAL tiers.
 * Returns a JSON-serialized `RestoreResult`.
 */
export declare function benchRestoreSnapshot(graph: BenchGraph, snapshotTier: BenchCheckpointSnapshotTier, walTier: BenchWalKvTier, targetSeq?: number | undefined | null): Promise<string>

/** Verify a WAL frame's checksum. Returns true if valid. */
export declare function benchVerifyWalFrameChecksum(frameJson: string): boolean

/** Compute a WAL frame's checksum (SHA-256 hex). Input: WAL frame JSON. */
export declare function benchWalFrameChecksum(frameJson: string): string

/** Compute the storage key for a WAL frame: `<prefix>/wal/<seq_padded>`. */
export declare function benchWalFrameKey(prefix: string, frameSeq: number): string

export declare const enum BuiltinBatchFn {
  MapAddOneBatch = 'MapAddOneBatch',
  MulTenThenComplete = 'MulTenThenComplete'
}

export declare const enum BuiltinFn {
  Identity = 'Identity',
  AddOne = 'AddOne'
}

export declare function globalCacheInt(nodeId: number): Promise<number>

export declare function globalEmitInt(nodeId: number, value: number): Promise<void>

export declare function globalRegisterDerivedIdentity(depIds: Array<number>): Promise<number>

export declare function globalRegisterStateInt(initial: number): Promise<number>

export declare function globalRustEmitLoop(nodeId: number, n: number): Promise<void>

export declare function globalSubscribeNoop(nodeId: number): Promise<number>

/**
 * Empty FFI round-trip. Measures pure napi-rs call overhead with no Rust work.
 * Bench: `for (let i = 0; i < N; i++) noop_call();` — divide by N for per-call cost.
 */
export declare function noopCall(): void

/**
 * FFI round-trip with one integer return. Measures napi-rs overhead with a
 * minimal payload (single i32). Real workloads always return *something* —
 * this captures the "common case" baseline that `noop_call` can't.
 */
export declare function noopCallReturningInt(): number

/**
 * JS-exposed `GraphRemoveAudit`. Mirrors `graphrefly_graph::GraphRemoveAudit`'s
 * flat counts; per-node detail isn't surfaced through the napi boundary
 * in v1 (parity scenarios only assert counts).
 */
export interface RemoveAuditJs {
  nodeCount: number
  mountCount: number
}

/** JS-exposed mirror of [`graphrefly_core::ResumeReport`]. */
export interface ResumeReportJs {
  replayed: number
  dropped: number
}

/** Smoke export — verifies napi-rs link works. */
export declare function version(): string
