//! napi-rs JavaScript bindings for `GraphReFly`.
//!
//! v0 FFI bench scope: minimal surface to measure (a) raw napi-rs call
//! overhead and (b) end-to-end emit throughput from JS through the Rust
//! dispatcher. Full feature parity (subscribe with JS callbacks, custom
//! equals, dynamic deps, set_deps, etc.) lands once v0 numbers justify it.
//!
//! # FFI cost-measurement strategy
//!
//! 1. `noop_call()` — empty FFI round-trip; measures pure napi-rs overhead.
//! 2. `rust_emit_loop(n)` — N emits inside Rust (single FFI call); measures
//!    Rust dispatcher cost amortized over many ops.
//! 3. `Core::emit(node_id, value)` — one FFI call per emit; measures end-to-end.
//!
//! Per-call FFI overhead = (T_js_loop / N) - (T_rust_loop / N), measured.

// **Per-crate unsafe-code carve-out** — relaxed from CLAUDE.md's
// workspace-wide `forbid(unsafe_code)` (Rust invariant 1) to `deny`
// ONLY for this crate (D072, user directive 2026-05-07: "no compat
// mode!"). Justification: napi-derive 3.x's `#[napi]` macro emits
// `#[allow(unsafe_code)]` on generated registration code. `forbid`
// rejects ALL `allow` overrides; `deny` rejects ad-hoc unsafe but
// permits the macro's explicit allows. No hand-written unsafe lives
// in this crate's source — every `allow` site is generated by
// napi-derive.
#![deny(unsafe_code)]
#![warn(rust_2018_idioms, unreachable_pub)]
#![warn(clippy::pedantic)]
#![allow(clippy::module_name_repetitions, clippy::missing_errors_doc)]

#[cfg(feature = "tracing")]
mod core_actor;

#[cfg(feature = "tracing")]
#[allow(unreachable_pub)] // napi-rs #[napi] items are pub for JS, not Rust-visible.
mod core_bindings;

// `BenchBatchContext` napi + parked-actor BatchOp loop (D289 / D288
// Path D). The tripwire (`assert_no_batch_handle`) is invoked from the
// three `bridge_sync*` entry points in operator_bindings,
// structures_bindings, and core_bindings (bridge_sync_unit).
#[cfg(feature = "tracing")]
#[allow(unreachable_pub)] // napi-rs #[napi] items are pub for JS, not Rust-visible.
mod batch_bindings;

#[cfg(feature = "operators")]
mod operator_bindings;

#[cfg(feature = "graph-codec")]
mod graph_bindings;

#[cfg(feature = "storage")]
#[allow(
    unreachable_pub,                     // napi-rs #[napi] items are pub for JS, not Rust-visible.
    clippy::needless_pass_by_value,      // napi-rs requires String not &str at the FFI boundary.
    clippy::wildcard_imports,            // napi::bindgen_prelude::* glob pattern.
    clippy::cast_possible_truncation,    // WAL_FRAME_SEQ_PAD usize→u32 is bounded.
    clippy::let_underscore_future,       // fire-and-forget spawn_blocking in Drop.
)]
mod storage_bindings;

#[cfg(feature = "structures")]
#[allow(
    unreachable_pub,
    clippy::needless_pass_by_value,
    clippy::wildcard_imports,
    clippy::cast_possible_truncation
)]
mod structures_bindings;

use napi_derive::napi;

/// Smoke export — verifies napi-rs link works.
#[napi]
#[must_use]
pub fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// Empty FFI round-trip. Measures pure napi-rs call overhead with no Rust work.
/// Bench: `for (let i = 0; i < N; i++) noop_call();` — divide by N for per-call cost.
#[napi]
pub const fn noop_call() {}

/// FFI round-trip with one integer return. Measures napi-rs overhead with a
/// minimal payload (single i32). Real workloads always return *something* —
/// this captures the "common case" baseline that `noop_call` can't.
#[napi]
#[must_use]
pub const fn noop_call_returning_int() -> i32 {
    42
}
